// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJ83d56leQU0B57hayc3ggDU4ISy89nc',
    appId: '1:707861951980:web:09a5c595e98a25f059fcc9',
    messagingSenderId: '707861951980',
    projectId: 'dimensionsixebike',
    authDomain: 'dimensionsixebike.firebaseapp.com',
    databaseURL: 'https://dimensionsixebike-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dimensionsixebike.appspot.com',
    measurementId: 'G-SLC9DY0YB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshMmlW-sN2uOoN8165BnByzBebbT7fnc',
    appId: '1:707861951980:android:931179f18ea6cbe359fcc9',
    messagingSenderId: '707861951980',
    projectId: 'dimensionsixebike',
    databaseURL: 'https://dimensionsixebike-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dimensionsixebike.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rZxwzzU13ibjU-4nnufRn2FQPgn4tMs',
    appId: '1:707861951980:ios:ef03eb0f0f09b6c159fcc9',
    messagingSenderId: '707861951980',
    projectId: 'dimensionsixebike',
    databaseURL: 'https://dimensionsixebike-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dimensionsixebike.appspot.com',
    iosBundleId: 'com.example.dimensionsixappmain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0rZxwzzU13ibjU-4nnufRn2FQPgn4tMs',
    appId: '1:707861951980:ios:cd9720139019a73659fcc9',
    messagingSenderId: '707861951980',
    projectId: 'dimensionsixebike',
    databaseURL: 'https://dimensionsixebike-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dimensionsixebike.appspot.com',
    iosBundleId: 'com.example.appEBike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkJ83d56leQU0B57hayc3ggDU4ISy89nc',
    appId: '1:707861951980:web:09a5c595e98a25f059fcc9',
    messagingSenderId: '707861951980',
    projectId: 'dimensionsixebike',
    authDomain: 'dimensionsixebike.firebaseapp.com',
    databaseURL: 'https://dimensionsixebike-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dimensionsixebike.appspot.com',
    measurementId: 'G-SLC9DY0YB6',
  );

}// TODO Implement this library.